procedure CodegenReset;
forward;
procedure CodegenSetOutput(Filename : string);
forward;
procedure OutEnumValuesFromCheckpoint(Checkpoint : TSDefinition);
forward;
procedure OutTypeDefinitionsFromCheckpoint(Checkpoint : TSDefinition);
forward;
procedure OutConstantArrayBegin;
forward;
procedure OutConstantArraySeparator;
forward;
procedure OutConstantArrayEnd;
forward;
procedure OutConstantRecordBegin;
forward;
procedure OutConstantRecordField(const Name : string);
forward;
procedure OutConstantRecordSeparator;
forward;
procedure OutConstantRecordEnd;
forward;
procedure OutVariableDefinition(VarPtr : TSDVariable; Location : TSExpression);
forward;
procedure OutConstantDefinitionBegin(VarPtr : TSDVariable);
forward;
procedure OutConstantDefinitionEnd;
forward;
procedure OutFunctionDeclaration(SrPtr : TSDSubroutine);
forward;
procedure OutFunctionDefinition(SrPtr : TSDSubroutine);
forward;
procedure OutFunctionEnd(SrPtr : TSDSubroutine);
forward;
procedure OutExpression(Expr : TSExpression);
forward;
procedure OutAssign(Lhs, Rhs : TSExpression);
forward;
procedure OutDeclareAndAssign(VarPtr : TSDVariable; Rhs : TSExpression);
forward;
procedure OutSequenceBegin;
forward;
procedure OutSequenceEnd;
forward;
procedure OutIf(Expr : TSExpression);
forward;
procedure OutElse;
forward;
procedure OutIfEnd;
forward;
procedure OutCaseBegin(CaseIndex : TSExpression);
forward;
procedure OutCaseStatementBegin(CaseLabel : TSExpression);
forward;
procedure OutCaseStatementEnd;
forward;
procedure OutCaseElseBegin;
forward;
procedure OutCaseElseEnd;
forward;
procedure OutCaseEnd;
forward;
procedure OutRepeatBegin;
forward;
procedure OutRepeatEnd(Expr : TSExpression);
forward;
procedure OutWhileBegin(Expr : TSExpression);
forward;
procedure OutWhileEnd;
forward;
procedure OutForBegin(Iter, FirstExpr, LastExpr : TSExpression;
                      Ascending : boolean);
forward;
procedure OutForEnd;
forward;
procedure OutExpressionStatement(Expr : TSExpression);
forward;
procedure OutEmptyStatement;
forward;
procedure OutProgramHeading(Name : string);
forward;
procedure OutProgramBegin;
forward;
procedure OutProgramEnd;
forward;
