#!/bin/sh -e

my_dir="$(dirname $0)"
PC="${PC:-${my_dir}/pascual}"
CC="${CC:-gcc}"
PINCDIR="${PINCDIR:-${my_dir}}"
PLIBDIR="${PLIBDIR:-${my_dir}}"

input=''
output=''
compile_only=

usage() {
  if [ -n "$1" ]
  then
    echo "$1" >&2
  fi
  echo "Usage: pascualc input [-o output] [-c]" >&2
  exit 1
}

parse_cmd() {
  while [ -n "$1" ]
  do
    case "$1" in
      '-c')
        compile_only=1
        ;;
      '-o')
        shift
        if [ -z "$1" ]; then usage "You must specify an output file" ; fi
        output="$1"
        ;;
      *)
        if [ -n "$input" ]; then usage "You can only specify one input file" ; fi
        input="$1"
        ;;
    esac
    shift
  done
  if [ -z "$input" ]; then usage "You must specify an input file" ; fi
  if [ -z "$output" ]
  then
    output="${input%.pas}"
    if [ -n "$compile_only" ]; then output="${output}.c" ; fi
    if [ "$input" = "$output" ]; then output="a.out" ; fi
  fi
  if [ "$input" = "$output" ]
  then
    usage "The input and output files should not be the same"
  fi
}

compile_to_c() {
  "$PC" "$1" -o "$2"
}

compile_to_out() {
  "$CC" -Os -I"$PINCDIR" -L"$PLIBDIR" $CFLAGS "$1" -o "$2" -lpascual -lm
}

parse_cmd "$@"

if [ -z "$compile_only" ]
then
  tmp_dir="$(mktemp -d -t pascualc.XXXXXXXXXX)"
  c_file="${tmp_dir}/source.c"
  trap 'rm -fR "$tmp_dir"' EXIT
else
  c_file="$output"
fi

compile_to_c "$input" "$c_file"

if [ -z "$compile_only" ]
then
  compile_to_out "$c_file" "$output"
fi
