function TypeName(TypePtr : TPsTypePtr) : string;
forward;

function IsUntyped(TypePtr : TPsTypePtr) : boolean;
forward;
function IsEnumType(TypePtr : TPsTypePtr) : boolean;
forward;
function IsOrdinalType(TypePtr : TPsTypePtr) : boolean;
forward;
function IsRecordType(TypePtr : TPsTypePtr) : boolean;
forward;
function IsArrayType(TypePtr : TPsTypePtr) : boolean;
forward;
function IsPointerType(TypePtr : TPsTypePtr) : boolean;
forward;
function IsStringyType(TypePtr : TPsTypePtr) : boolean;
forward;
function IsStringType(TypePtr : TPsTypePtr) : boolean;
forward;
function IsIntegerType(TypePtr : TPsTypePtr) : boolean;
forward;
function IsNumericType(TypePtr : TPsTypePtr) : boolean;
forward;
