function TypeName(TypePtr : TSDType) : string;
forward;

function IsUntyped(TypePtr : TSDType) : boolean;
forward;
function IsEnumType(TypePtr : TSDType) : boolean;
forward;
function IsOrdinalType(TypePtr : TSDType) : boolean;
forward;
function IsRecordType(TypePtr : TSDType) : boolean;
forward;
function IsArrayType(TypePtr : TSDType) : boolean;
forward;
function IsPointerType(TypePtr : TSDType) : boolean;
forward;
function IsStringyType(TypePtr : TSDType) : boolean;
forward;
function IsStringType(TypePtr : TSDType) : boolean;
forward;
function IsIntegerType(TypePtr : TSDType) : boolean;
forward;
function IsNumericType(TypePtr : TSDType) : boolean;
forward;
function IsFileType(TypePtr : TSDType) : boolean;
forward;
function IsGenericFileType(TypePtr : TSDType) : boolean;
forward;
