function PfDispose_Parse(FnExpr : TExpression) : TExpression;
forward;
function PfNew_Parse(FnExpr : TExpression) : TExpression;
forward;
function PfOrd_Parse(FnExpr : TExpression) : TExpression;
forward;
function PfOrd(Arg : TExpression) : TExpression;
forward;
function PfPred_Parse(FnExpr : TExpression) : TExpression;
forward;
function PfPred(Arg : TExpression) : TExpression;
forward;
function PfRead_Parse(FnExpr : TExpression) : TExpression;
forward;
function PfSucc_Parse(FnExpr : TExpression) : TExpression;
forward;
function PfSucc(Arg : TExpression) : TExpression;
forward;
function PfStr_Parse(FnExpr : TExpression) : TExpression;
forward;
function PfVal_Parse(FnExpr : TExpression) : TExpression;
forward;
function PfWrite_Parse(FnExpr : TExpression) : TExpression;
forward;
