function ExOpNeg(Expr : TSExpression) : TSExpression;
forward;
function ExOpAdd(Left, Right : TSExpression) : TSExpression;
forward;
function ExOpSub(Left, Right : TSExpression) : TSExpression;
forward;
function ExOpMul(Left, Right : TSExpression) : TSExpression;
forward;
function ExOpDivReal(Left, Right : TSExpression) : TSExpression;
forward;
function ExOpDivInt(Left, Right : TSExpression) : TSExpression;
forward;
function ExOpMod(Left, Right : TSExpression) : TSExpression;
forward;

function ExOpNot(Expr : TSExpression) : TSExpression;
forward;
function ExOpAnd(Left, Right : TSExpression) : TSExpression;
forward;
function ExOpOr(Left, Right : TSExpression) : TSExpression;
forward;
function ExOpXor(Left, Right : TSExpression) : TSExpression;
forward;

function ExOpShl(Left, Right : TSExpression) : TSExpression;
forward;
function ExOpShr(Left, Right : TSExpression) : TSExpression;
forward;

function ExOpIn(Left, Right : TSExpression) : TSExpression;
forward;
function ExOpEq(Left, Right : TSExpression) : TSExpression;
forward;
function ExOpNe(Left, Right : TSExpression) : TSExpression;
forward;
function ExOpLt(Left, Right : TSExpression) : TSExpression;
forward;
function ExOpGt(Left, Right : TSExpression) : TSExpression;
forward;
function ExOpLtEq(Left, Right : TSExpression) : TSExpression;
forward;
function ExOpGtEq(Left, Right : TSExpression) : TSExpression;
forward;

function ExOpOrd(Expr : TSExpression) : TSExpression;
forward;
function ExOpPred(Expr : TSExpression) : TSExpression;
forward;
function ExOpSucc(Expr : TSExpression) : TSExpression;
forward;
