function ExOpNeg(Expr : TExpression) : TExpression;
forward;
function ExOpAdd(Left, Right : TExpression) : TExpression;
forward;
function ExOpSub(Left, Right : TExpression) : TExpression;
forward;
function ExOpMul(Left, Right : TExpression) : TExpression;
forward;
function ExOpDivReal(Left, Right : TExpression) : TExpression;
forward;
function ExOpDivInt(Left, Right : TExpression) : TExpression;
forward;
function ExOpMod(Left, Right : TExpression) : TExpression;
forward;

function ExOpNot(Expr : TExpression) : TExpression;
forward;
function ExOpAnd(Left, Right : TExpression) : TExpression;
forward;
function ExOpOr(Left, Right : TExpression) : TExpression;
forward;
function ExOpXor(Left, Right : TExpression) : TExpression;
forward;

function ExOpShl(Left, Right : TExpression) : TExpression;
forward;
function ExOpShr(Left, Right : TExpression) : TExpression;
forward;

function ExOpIn(Left, Right : TExpression) : TExpression;
forward;
function ExOpEq(Left, Right : TExpression) : TExpression;
forward;
function ExOpNe(Left, Right : TExpression) : TExpression;
forward;
function ExOpLt(Left, Right : TExpression) : TExpression;
forward;
function ExOpGt(Left, Right : TExpression) : TExpression;
forward;
function ExOpLtEq(Left, Right : TExpression) : TExpression;
forward;
function ExOpGtEq(Left, Right : TExpression) : TExpression;
forward;

function ExOpOrd(Expr : TExpression) : TExpression;
forward;
function ExOpPred(Expr : TExpression) : TExpression;
forward;
function ExOpSucc(Expr : TExpression) : TExpression;
forward;
